# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Relay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Relay
  
  # RxSwift
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  # RxAlamofire
  pod 'RxAlamofire'

  # Moya
  pod 'Moya/RxSwift', '~> 15.0'
  
end
